[default.extend-words]
# noice.nvim
noice = "noice"
# vim keymap
enew = "enew"
# starship config
edn = "edn"
esy = "esy"
ane = "ane"
nane = "nane"
# macOS Big Sur
sur = "sur"
# fish abbr `chezmoi cd`
chec = "chec"
# key mapping in dot_config/nvim/lua/plugins/telescope-nvim.lua
fo = "fo"
# dot_config/nvim/lua/plugins/configs/nvim-tree/actions.lua
nd = "nd"
# dot_mimikun-pkglists
serie = "serie"
tre = "tre"
tere = "tere"
# stylus lang ext: https://github.com/stylus/stylus
styl = "styl"
# dot_config/fish/completions/starship.fish
mis = "mis"
# dot_config/starship/starship.toml
typ = "typ"
# iterm2
# dot_config/presenterm/config.yaml
iterm = "iterm"
# dot_config/fish/completions/srgn.fish
# `Hashi` is HashiCorp
Hashi = "Hashi"

[files]
extend-exclude = [
  # NOTE: DO NOT expect an upstream fix
  "dot_config/fish/completions/deno.fish",
  "dot_config/nvim/lua/plugins/telekasten-nvim/init.lua",
  "dot_config/ghostty/*",
  "dot_config/foot/foot.ini",
  "dot_config/moe/moerc.toml",
  "dot_config/fish/completions/sake.fish",
  "dot_mimikun-pkglists/linux_pip_packages.txt",
  "dot_config/glide/glide.d.ts",
  "dot_config/yazi/theme.toml",
  # error: `informations` should be `information`
  "dot_config/fish/completions/helix.fish",
  "dot_config/fish/completions/hx.fish",
  # NOTE: DO NOT expect an upstream fix
  # NOTE: Experimental software and no fixes are expect
  "dot_config/fish/completions/fish-lsp.fish",
  # NOTE: Unmaintained and no upstream fixes
  "dot_config/pipr/pipr.toml",
  "dot_config/gotop/gotop.conf",
  # NOTE: Game settings
  "game_settings/Apex_Legends",
  "game_settings/CookieClicker",
  # NOTE: has many typos
  "dot_config/private_fcitx5/private_conf/private_cached_layouts",
  "dot_config/nvim/dotfyle.json",
  "CHANGELOG.md",
  "dot_config/nvim/lua/plugins/nvim-orgmode/org-list-opts.lua",
  "dot_config/nvim/lua/unused/*",
  "dot_config/nvim/lua/plugins/org-list-nvim/opts.lua",
  "dot_config/nvim/lua/plugins/org-list-nvim/keys.lua",
]
