[default.extend-words]
# noice.nvim
noice = "noice"
# vim keymap
enew = "enew"
# starship config
edn = "edn"
esy = "esy"
ane = "ane"
nane = "nane"
# macOS Big Sur
sur = "sur"
# fish abbr `chezmoi cd`
chec = "chec"
# key mapping in dot_config/nvim/lua/plugins/telescope-nvim.lua
fo = "fo"
# telescope-nvim
tabe = "tabe"
# dot_config/nvim/lua/plugins/configs/nvim-tree/actions.lua
nd = "nd"

[files]
extend-exclude = [
  # NOTE: DO NOT expect an upstream fix
  "dot_config/foot/foot.ini",
  "dot_config/moe/moerc.toml",
  # NOTE: DO NOT expect an upstream fix
  # NOTE: PR done: https://github.com/dharmx/telescope-media.nvim/pull/31
  "dot_config/nvim/lua/plugins/configs/telescope-nvim/media.lua",
  # NOTE: DO NOT expect an upstream fix
  # NOTE: PR done: https://github.com/rcarriga/nvim-dap-ui/pull/379
  "dot_config/nvim/lua/plugins/nvim-dap-ui.lua",
  # NOTE: DO NOT expect an upstream fix
  # NOTE: Experimental software and no fixes are expect
  "dot_config/fish/completions/fish-lsp.fish",
  # NOTE: Unmaintained and no upstream fixes
  "dot_config/pipr/pipr.toml",
  "dot_config/gotop/gotop.conf",
  # NOTE: Game settings
  "game_settings/Apex_Legends",
  "game_settings/CookieClicker",
  # NOTE: has many typos
  "dot_config/nvim/dotfyle.json",
]
