[tools]
dotnet-core = "latest"
lua = "latest"
luajit = "latest"
tig = "latest"
vim = "latest"
ruby = "latest"
neovim = "0.10.0"
node = "20"
powershell-core = "7.4"
python = "3"
zig = "latest"

[plugins]
luajit = "https://github.com/smashedtoatoms/asdf-luaJIT.git"
tig = "https://github.com/koketani/asdf-tig.git"
# https://github.com/tsuyoshicho/asdf-vim has bug
vim = "https://github.com/mimikun/asdf-vim.git"
