[tools]
dotnet-core = "latest"
erlang = "latest"
gleam = "latest"
go = "latest"
lua = "5.1.5"
luajit = "2.0.5--2.4.4"
node = [
    # lts = 20
    "20",
    "21",
    "22",
]
powershell-core = [
    "latest",
    "7.4",
]
python = [
    "latest",
    # mise cannot install python v2
    #"2",
    "3",
]
ruby = "latest"
tig = "latest"
vim = [
    "latest",
    "ref:master",
]
zig = [
    "ref:master",
    "latest",
]

# npm backend
"npm:npkill" = "latest"
"npm:prettier" = "latest"
"npm:commitizen" = "latest"
"npm:cz-conventional-changelog-ja" = "latest"

# pipx backend
"pipx:anufrievroman/calcure" = "latest"
"pipx:sauljabin/kaskade" = "latest"
"pipx:ChrisBuilds/moneyterm" = "latest"
"pipx:python-poetry/poetry" = "latest"
"pipx:darrenburns/posting" = "latest"
"pipx:pocker-tui" = "latest"
"pipx:gptme" = "latest"

# go backend
"go:git.sr.ht/~xenrox/hut" = "latest"
"go:github.com/dhth/act3" = "latest"
"go:github.com/monochromegane/afa" = "latest"
"go:github.com/monochromegane/afa-tui" = "latest"
"go:github.com/bschaatsbergen/cidr" = "latest"
"go:github.com/danvergara/dblab" = "latest"
"go:github.com/davidrjenni/reftools/cmd/fillstruct" = "latest"
"go:github.com/jon4hz/fztea" = "latest"
"go:github.com/muandane/goji" = "latest"
"go:github.com/umlx5h/gtrash" = "latest"
"go:github.com/nao1215/gup" = "0.27.5"
"go:github.com/dhth/hours" = "latest"
"go:github.com/gchaincl/httplab/cmd/httplab" = "latest"
"go:github.com/koron/iferr" = "latest"
"go:github.com/vladimirvivien/ktop" = "latest"
"go:github.com/jorgerojas26/lazysql" = "latest"
"go:github.com/szktkfm/mdtt/cmd/mdtt" = "latest"
"go:github.com/maaslalani/nap" = "latest"
"go:github.com/dhth/omm" = "latest"
"go:github.com/dhth/prs" = "latest"
"go:github.com/mrusme/reader" = "latest"
"go:github.com/noperator/sol/cmd/sol" = "latest"
"go:github.com/neilotoole/sq" = "latest"
"go:github.com/ddddddO/packemon/cmd/packemon" = "latest"
"go:github.com/marwanhawari/stew" = "latest"
"go:github.com/pouriyajamshidi/tcping" = "latest"

[plugins]
luajit = "https://github.com/smashedtoatoms/asdf-luaJIT.git"
tig = "https://github.com/koketani/asdf-tig.git"
vim = "https://github.com/mimikun/asdf-vim.git"

[settings]
activate_aggressive = false
asdf = true
asdf_compat = true
disable_tools = []
libgit2 = true
paranoid = false
status = { missing_tools = "if_other_versions_installed", show_env = false, show_tools = false }
use_versions_host = true
vfox = false
legacy_version_file = true
legacy_version_file_disable_tools = []
always_keep_download = false
always_keep_install = false
plugin_autoupdate_last_check_duration = "7d"
trusted_config_paths = []
verbose = false
#http_timeout = 30
jobs = 1
raw = false
yes = false
not_found_auto_install = true
experimental = true
all_compile = false
pipx_uvx = true
cargo_binstall = false
task_output = "prefix"
shorthands_file = ""
disable_default_shorthands = false
#disable_hints = []
color = true
#go_default_packages_file = "~/.default-go-packages"
#go_download_mirror = "https://dl.google.com/go"
#go_repo = "https://github.com/golang/go"
#go_set_gopath = false
#go_set_goroot = true
#go_skip_checksum = false
#node_compile = false
python_compile = false
#python_default_packages_file = "~/.default-python-packages"
#python_pyenv_repo = "https://github.com/pyenv/pyenv.git"
quiet = false
#ci = false
#debug = false
#trace = false
#log_level = "info"
python_venv_auto_create = false
