[tools]
dotnet-core = "latest"
lua = "latest"
luajit = "latest"
tig = "latest"
ruby = "latest"
vim = [
    "latest",
    "ref:master",
]
neovim = [
    "nightly",
    "ref:master",
    "stable",
    "latest",
]
node = [
    # lts = 20
    "20",
    "21",
    "22",
]
powershell-core = [
    "latest",
    "7.4",
]
python = [
    "latest",
    # mise cannot install python v2
    #"2",
    "3",
]
zig = [
    "ref:master",
    "latest",
]

[plugins]
luajit = "https://github.com/smashedtoatoms/asdf-luaJIT.git"
tig = "https://github.com/koketani/asdf-tig.git"
# https://github.com/tsuyoshicho/asdf-vim has bug
vim = "https://github.com/mimikun/asdf-vim.git"
