[tools]
dotnet-core = "latest"
erlang = "latest"
ruby = "latest"
lua = "5.5.0"
node = [
  "lts",
  "22",
  "latest",
  "23",
]
python = [
  "3.12",
  "latest",
  "3",
  "3.11",
  "3.13",
]
vim = [
  "ref:master",
  "latest",
]
zig = [
  "master",
  "latest",
]

[settings]
activate_aggressive = true
# TODO: check
auto_install = true
# TODO: check
exec_auto_install = true
experimental = true
idiomatic_version_file_enable_tools = [
  "crystal",
  "elixir",
  "go",
  "java",
  "node",
  "python",
  "ruby",
  "terraform",
  "yarn",
]
jobs = 1
lockfile = true
not_found_auto_install = true
cargo.binstall = false
npm.bun = true
pipx.uvx = true
status.missing_tools = "if_other_versions_installed"
