[colors]
cursor = { text = "CellBackground", cursor = "CellForeground" }
vi_mode_cursor = { text = "CellBackground", cursor = "CellForeground" }
line_indicator = { foreground = "None", background = "None" }
footer_bar = { foreground = "#181818", background = "#d8d8d8" }
selection = { text = "CellBackground", background = "CellForeground" }
indexed_colors = []
transparent_background_colors = false
draw_bold_text_with_bright_colors = false

[colors.primary]
foreground = "#d8d8d8"
background = "#181818"
dim_foreground = "#828482"
bright_foreground = "None"

[colors.search]
matches = { foreground = "#181818", background = "#ac4242" }
focused_match = { foreground = "#181818", background = "#f4bf75" }

[colors.hints]
start = { foreground = "#181818", background = "#f4bf75" }
end = { foreground = "#181818", background = "#ac4242" }

[colors.normal]
black = "#181818"
red = "#ac4242"
green = "#90a959"
yellow = "#f4bf75"
blue = "#6a9fb5"
magenta = "#aa759f"
cyan = "#75b5aa"
white = "#d8d8d8"

[colors.bright]
black = "#6b6b6b"
red = "#c55555"
green = "#aac474"
yellow = "#feca88"
blue = "#82b8c8"
magenta = "#c28cb8"
cyan = "#93d3c3"
white = "#f8f8f8"

[colors.dim]
black = "#0f0f0f"
red = "#712b2b"
green = "#5f6f3a"
yellow = "#a17e4d"
blue = "#456877"
magenta = "#704d68"
cyan = "#4d7770"
white = "#8e8e8e"
